# Generated by Django 2.1.7 on 2019-04-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoassets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoassetgroup',
            name='availability_requirement',
            field=models.CharField(default='H', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoassetgroup',
            name='confidentiality_requirement',
            field=models.CharField(default='H', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoassetgroup',
            name='integrity_requirement',
            field=models.CharField(default='H', max_length=255),
            preserve_default=False,
        ),
    ]
