# Generated by Django 2.1.7 on 2019-03-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nistapplicationoption',
            name='release',
        ),
    ]
