# Generated by Django 2.1.7 on 2019-03-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infoassets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('note', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'business_activity',
            },
        ),
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('note', models.TextField(max_length=255)),
                ('business_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.BusinessActivity')),
                ('info_asset_group', models.ManyToManyField(to='infoassets.InfoAssetGroup')),
            ],
            options={
                'db_table': 'system_activity',
            },
        ),
    ]
