# Generated by Django 2.1.7 on 2019-03-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemactivity',
            name='system_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.SystemRole'),
        ),
        migrations.AddField(
            model_name='businessactivity',
            name='business_role',
            field=models.ManyToManyField(to='roles.BusinessRole'),
        ),
    ]
