# Generated by Django 2.1.7 on 2019-03-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190325_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='business_role',
            field=models.ManyToManyField(blank=True, to='roles.BusinessRole'),
        ),
    ]
