# Generated by Django 2.1.7 on 2019-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_vulnerability'),
        ('hardware', '0010_hardware_vulnerability'),
        ('activities', '0003_auto_20190325_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemactivity',
            name='application',
            field=models.ManyToManyField(to='applications.Application'),
        ),
        migrations.AddField(
            model_name='systemactivity',
            name='operating_system',
            field=models.ManyToManyField(to='hardware.OperatingSystem'),
        ),
    ]
