# Generated by Django 2.1.7 on 2019-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20190426_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemactivity',
            name='monthly_value',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
            preserve_default=False,
        ),
    ]
