# Generated by Django 2.1.7 on 2019-04-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_systemactivity_monthly_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemactivity',
            old_name='monthly_value',
            new_name='daily_value',
        ),
    ]
