# Generated by Django 2.1.7 on 2019-03-16 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NISTHardwareOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('update', models.CharField(blank=True, max_length=255, null=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('sw_edition', models.CharField(blank=True, max_length=255, null=True)),
                ('target_sw', models.CharField(blank=True, max_length=255, null=True)),
                ('target_hw', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist_hardware_option',
            },
        ),
        migrations.CreateModel(
            name='NISTOperatingSystemOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('update', models.CharField(blank=True, max_length=255, null=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('sw_edition', models.CharField(blank=True, max_length=255, null=True)),
                ('target_sw', models.CharField(blank=True, max_length=255, null=True)),
                ('target_hw', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist_operating_system_option',
            },
        ),
        migrations.CreateModel(
            name='NISTVendorOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist_vendor_option',
            },
        ),
        migrations.AddField(
            model_name='nistoperatingsystemoption',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.NISTVendorOption'),
        ),
        migrations.AddField(
            model_name='nisthardwareoption',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.NISTVendorOption'),
        ),
    ]
