# Generated by Django 2.1.7 on 2019-03-18 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('update', models.CharField(blank=True, max_length=255, null=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('sw_edition', models.CharField(blank=True, max_length=255, null=True)),
                ('target_sw', models.CharField(blank=True, max_length=255, null=True)),
                ('target_hw', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('cpe_string', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hardware',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('update', models.CharField(blank=True, max_length=255, null=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('sw_edition', models.CharField(blank=True, max_length=255, null=True)),
                ('target_sw', models.CharField(blank=True, max_length=255, null=True)),
                ('target_hw', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('cpe_string', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'operating_system',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Vendor'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.Vendor'),
        ),
    ]
