# Generated by Django 2.1.7 on 2019-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_hardware_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='note',
            field=models.TextField(default='note', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hardware',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
