# Generated by Django 2.1.7 on 2019-03-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware', '0006_auto_20190321_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('is_third_party', models.BooleanField(default=False)),
                ('hardware', models.ManyToManyField(to='hardware.Hardware')),
            ],
            options={
                'db_table': 'system',
            },
        ),
    ]
