# Generated by Django 2.1.7 on 2019-03-26 02:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NISTCVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pullled', models.DateTimeField(auto_now=True, verbose_name='date pulled')),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.System')),
            ],
            options={
                'db_table': 'nist_cve',
            },
        ),
    ]
