# Generated by Django 2.1.7 on 2019-04-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_auto_20190325_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nistcve',
            name='system',
        ),
    ]
