# Generated by Django 2.1.7 on 2019-04-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0004_nistcve_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nistcve',
            name='date_pullled',
        ),
        migrations.RemoveField(
            model_name='nistcve',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='nistcve',
            name='system',
        ),
        migrations.AddField(
            model_name='nistcve',
            name='cve_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nistcve',
            name='date_modified',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nistcve',
            name='date_published',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nistcve',
            name='description',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
