# Generated by Django 2.1.7 on 2019-04-16 12:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0007_auto_20190415_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvev2impact',
            name='ac_insuf_info',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='access_complexity',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='access_vector',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='authentication',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='availability_impact',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='base_score',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='confidentiality_impact',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='exploitability_score',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='impact_score',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='integrity_impact',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='obtain_all_privilege',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='obtain_other_privilege',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='obtain_user_privilege',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='user_interaction_required',
        ),
        migrations.RemoveField(
            model_name='cvev2impact',
            name='vector_string',
        ),
        migrations.AddField(
            model_name='cvev2impact',
            name='v2_impact_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
