# Generated by Django 2.1.7 on 2019-04-24 20:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0009_vulnerability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvev3impact',
            name='attack_complexity',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='attack_vector',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='availability_impact',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='base_score',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='base_severity',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='confidentiality_impact',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='exploitability_score',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='impact_score',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='integrity_impact',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='privileges_required',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='user_interaction',
        ),
        migrations.RemoveField(
            model_name='cvev3impact',
            name='vector_string',
        ),
        migrations.AddField(
            model_name='cvev3impact',
            name='v3_impact_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvev2impact',
            name='cve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.NISTCVE'),
        ),
        migrations.AlterField(
            model_name='cvev3impact',
            name='cve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.NISTCVE'),
        ),
    ]
